# do not touch this line
configVersion: 2

description: Makes the Matrix Rainbow-y
keywords: ''
name: rainbowMode
shortName: rainbowMode
displayName: Rainbow Mode

# Sliders to control speed and direction
screens:
  - - angle
  - - refresh
widgets:
    angle:
        control: range
        event: angleDisplace
        min: -60
        max: 60
        label: Angle Diplacement
    refresh:
        control: range
        event: reRenderTime
        min: 50
        max: 1000
        label: Refresh Time
